# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'douhan' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'YouTubePlayer'
pod 'SnapKit'
pod 'AudioKit'

  # Pods for douhan

end
